## **`Determinant and Transpose of a 3x3 Matrix Using Python`**

`This Python script demonstrates how to calculate the determinant and the transpose of a 3x3 matrix using numpy and a custom determinant function.`

1. `The program prompts the user to input values for a 3x3 matrix. Each value is stored in variables (a to i) corresponding to the matrix elements:`
  ```bash
  | a  b  c |
  | d  e  f |
  | g  h  i |

2. *`The matrix is stored as a 2D NumPy array:`*
 ```python
    np.array([[a, b, c], [d, e, f], [g, h, i]])

3. *`The determinant of a 3x3 matrix is calculated using a custom function determinate_3x3:`*
 ```python
 def determinate_3x3(a,b,c,d,e,f,g,h,i):
  return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
  
  Formula: Determinant=a(ei−fh)−b(di−fg)+c(dh−eg)

4. *`The result is printed:`*
 ```python
    print("\nDeterminant results:", result)

5. *`The transpose of the matrix is computed using the .T property of the NumPy array:`*
  ```python
    T = A.T
    print("\nTranspose of A matrix:\n")
    print(T)


In [2]:
import numpy as np

a = float(input("Enter a:"))
b = float(input("Enter b:"))
c = float(input("Enter c:"))

d = float(input("Enter d:"))
e = float(input("Enter e:"))
f = float(input("Enter f:"))

g = float(input("Enter g:"))
h = float(input("Enter h:"))
i = float(input("Enter i:"))

A = np.array([[a, b, c], [d, e, f], [g, h, i]])

print("\nDeterminable Matrix\n")
print(A)

def determinate_3x3(a,b,c,d,e,f,g,h,i):
  return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)

result = determinate_3x3(a,b,c,d,e,f,g,h,i)
print("\nDeterminat results:",result)
print("\nTranspose of A matrix:\n")
T = A.T
print(T)

Enter a:-1
Enter b:2
Enter c:7
Enter d:2
Enter e:-1
Enter f:-1
Enter g:3
Enter h:5
Enter i:2

Determinable Matrix

[[-1.  2.  7.]
 [ 2. -1. -1.]
 [ 3.  5.  2.]]

Determinat results: 74.0

Transpose of A matrix:

[[-1.  2.  3.]
 [ 2. -1.  5.]
 [ 7. -1.  2.]]
